Math magicians: components project implementation
habasm/Math-Magicians pull request #2
Opened 2023-02-15 13:15 UTC by habasm

# This is Components task of the math-magicians project by @habasm 
-In this project, I am continued with the development of the Math Magicians app. I also added a React component that will hold the core functionality: a calculator.
-##actions
-  Used React components.
-  Used React props.
- Used React state.

![image](https://user-images.githubusercontent.com/111062079/219037565-c5ae6546-1e2a-4d7d-8533-981a509c83b5.png)

2023-02-15 13:32 UTC, julie-ify requested changes
## Hi @habasm,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 13:32 UTC, julie-ify commented on src/App.js
> +}
- [ ] As listed in your requirements, you are to use functional components. Kindly refactor this component to a functional one instead.

2023-02-15 13:32 UTC, julie-ify commented on README.md
- [ ] Kindly remove these files as they would not be needed and we want to keep our codebase clean.

  ![oas](https://user-images.githubusercontent.com/81468675/219040453-7ba5ea9a-ab59-4c1d-8f77-30758f0e6518.jpg)

2023-02-15 13:32 UTC, julie-ify commented on src/components/Calculator-class-based.js
> +    id: uuidv4(),
- [ ] I don't think we need this component. It is a duplicate of the functional component - except it is class-based. Kindly remove this component.

2023-02-16 05:38 UTC, habasm commented
## Dear @julie-ify, Thanks for comments and I am  fixed the following points
### ✔️ fixations
- unnecessary files removed 
- duplicated code removed
- codding's is manipulated as functional component instead of class component

2023-02-16 05:57 UTC, KayLemba approved these changes
[# STATUS: APPROVED :green_circle: :clap: 

Hello @habasm , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R
- [x] Proffessional README








 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

2023-02-16 06:10 UTC, merged